# Generated by Django 6.0.2 on 2026-02-16 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ai_agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=51)),
                ('kasbi', models.CharField(max_length=51)),
                ('shaxsiyat', models.TextField()),
                ('icon', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('kimdan', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')])),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt.ai_agent')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
